### PR TITLE
Importer project cleanup

### PR DESCRIPTION
**Pull request by kellnerd**
Continuation of #40, depends on https://github.com/metabrainz/bookbrainz-data-js/pull/309

Most commits are only deleting unused stuff, so this one should be easy to review.
Additionally I've fixed a rare bug in ca8f7515c79d205bbc47aac65f33ef8f2627e1ce, improved a few types and resolved a few linter errors. (Now that the outdated legacy code is gone, the eslint output finally became clearer as it contained less irrelevant messages.)

- [ ] Drop useless [error wrappers](https://github.com/kellnerd/bookbrainz-utils/blob/11962796822a3dbdc605c7acd70834a9a2cec6b0/importer/src/helpers/errors.ts) (WIP)
- [x] Delete old [OL producer CLI](https://github.com/kellnerd/bookbrainz-utils/blob/11962796822a3dbdc605c7acd70834a9a2cec6b0/importer/src/openLibrary/producer/index.js) (replaced by [new producer CLI](https://github.com/kellnerd/bookbrainz-utils/blob/11962796822a3dbdc605c7acd70834a9a2cec6b0/importer/src/openLibrary/import.ts))
- [x] Delete old [exploration tool](https://github.com/kellnerd/bookbrainz-utils/blob/11962796822a3dbdc605c7acd70834a9a2cec6b0/importer/src/openLibrary/exploration) (used to collect statistics about available JSON attributes in OL dumps) and its [old queue dependency](https://github.com/kellnerd/bookbrainz-utils/blob/11962796822a3dbdc605c7acd70834a9a2cec6b0/importer/src/queue/index.ts)
- [x] Delete [`asyncCluster`](https://github.com/kellnerd/bookbrainz-utils/blob/11962796822a3dbdc605c7acd70834a9a2cec6b0/importer/src/asyncCluster) (currently no replacement) and uninstall `async` npm package
- [x] Move [general parser types](https://github.com/kellnerd/bookbrainz-utils/blob/11962796822a3dbdc605c7acd70834a9a2cec6b0/importer/src/parser.ts) into ~a subfolder~ bb-data (15abafc99d283683f8b156351a003cb8cf4257e7 depends on https://github.com/metabrainz/bookbrainz-data-js/pull/309, could be dropped from this PR if necessary)
- [ ] Move [queue module](https://github.com/kellnerd/bookbrainz-utils/blob/11962796822a3dbdc605c7acd70834a9a2cec6b0/importer/src/queue.ts) into a subfolder (when the old queue is gone)
- [ ] Improve folder structure, e.g. flatten producer directory
- [ ] Convert [identifier mapping](https://github.com/kellnerd/bookbrainz-utils/blob/11962796822a3dbdc605c7acd70834a9a2cec6b0/importer/src/helpers/mapping.ts) into an enum?
- [x] Update or delete obsolete [README for the config file](https://github.com/kellnerd/bookbrainz-utils/blob/11962796822a3dbdc605c7acd70834a9a2cec6b0/importer/config/README.md) once the implementation is stable?
- [x] Update or delete obsolete [package.json scripts](https://github.com/kellnerd/bookbrainz-utils/blob/11962796822a3dbdc605c7acd70834a9a2cec6b0/importer/package.json) once the implementation is stable

As you can see above, I haven't moved any files yet as I'm still unsure what would be a good folder structure. Until we have found one, I would prefer not to move any files as this only makes it very hard to trace the git history of a file. https://github.com/metabrainz/bookbrainz-utils/commit/896560496d968cd9dbf6dd640cac5b60fdefdd99 is still annoying me from time to time in this regard. (I wonder why it was decided to have two unrelated project in one repository, that has tripped me a few times already when I accidentally ran npm or yarn inside the root directory...)

### CODE REVIEW

**Comment by MonkeyDo** [comment]
Looks all good so far !

I agree with moving files in another PR. Happy to have an IRC chat to figure out folder structure if you want.

> Convert [identifier mapping](https://github.com/kellnerd/bookbrainz-utils/blob/11962796822a3dbdc605c7acd70834a9a2cec6b0/importer/src/helpers/mapping.ts) into an enum?

It might indeed make sense to do that.
Looking at you, [identifier-links.js](https://github.com/metabrainz/bookbrainz-site/blob/d1213087e81f1f27c40fcf8be90e7297324e4cb7/src/client/components/pages/entities/identifiers-links.js#L27-L48)
We could deploy that as a minor version of the ORM after deploying the TS cleanup major version, if that works for you.

**Comment by kellnerd** [comment]
> Happy to have an IRC chat to figure out folder structure if you want.

Let's postpone that until I've got the OpenLibrary importer (including relationships) working, then I will have a better understanding how complex each producer implementation will be and how many common code is left which does not belong into bb-data.
Currently it's hard to make a call whether we should have a simple "one flat folder per producer" hierarchy and simply move `queue.ts` into `helpers/` or its own folder.
The only thing which I'm certain about is that it would make sense to have only executable scripts like `bbiq.ts` directly inside the `src/` folder.

> We could deploy that as a minor version of the ORM after deploying the TS cleanup major version, if that works for you.

Since the identifier mapping enum will be used by both bb-site and bb-utils, it should definitely live in bb-data in the end.
I agree with having that in a later ORM release only as it's not that relevant for my GSoC project.
So far I've only done the refactorings which also improve DX for GSoC and only kept a list of all the other things that I've noticed which could also be improved (there are quite a lot).

**Comment by MonkeyDo** [comment]
So does that mean that work on this PR is done, and it's ready for final review and merging?

**Comment by kellnerd** [comment]
Yes, I would say the work is done.
After https://github.com/metabrainz/bookbrainz-data-js/pull/309 has been merged and the new version has been released on npm, I will do a version bump commit here and then it can be merged.

**Review by MonkeyDo — APPROVED** [review]
I set up everything from scratch following the instructions in the readme, and successfully produced messages for 100 authors, then started the consumer which successfully consumed 100 messages.
Everything is working fine and the code looks much cleaner, nice work !


Even though I get errors on insertion in the DB, the tool works great and the CLI is very usable (testing the failure queue while I was at it).

IMO the default mechanism should be to post failures to the failure queue, with the ability to  pass an option to change the failure queue name or disable it. (probably fine to change this in a separate PR once we've used the tool a bit more, maybe my opinion was actually 💩 )

**Pull request merged**
